# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'


steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    configuration: 'release'
    platform: 'Any CPU'
    clean: true
    restoreNugetPackages: true

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    buildProperties: 'outputType=Library'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: dotnet_uipath_lib_drop'
  inputs:
    ArtifactName: 'dotnet_uipath_lib_drop'
